name: CI
on:
  push:
jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SRM_DEVOPS_DEPLOY_KEY: ${{ secrets.SRM_DEVOPS_DEPLOY_KEY }}
        IMAGE_NAME: srm-frontend
        CHART_NAME: site
      run: |
        BUILD_ARGS=""
        if docker pull "ghcr.io/whiletrue-industries/${IMAGE_NAME}:latest"; then
          BUILD_ARGS="--cache-from ghcr.io/whiletrue-industries/${IMAGE_NAME}:latest"
        fi
        docker build -t api $BUILD_ARGS . &&\
        echo "${GITHUB_TOKEN}" | docker login https://ghcr.io -u whiletrue-industries --password-stdin &&\
        docker tag api "ghcr.io/whiletrue-industries/${IMAGE_NAME}:${GITHUB_SHA}" &&\
        docker push "ghcr.io/whiletrue-industries/${IMAGE_NAME}:${GITHUB_SHA}" &&\
        if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
          docker tag api "ghcr.io/whiletrue-industries/${IMAGE_NAME}:latest" &&\
          docker push "ghcr.io/whiletrue-industries/${IMAGE_NAME}:latest" &&\
          echo "${SRM_DEVOPS_DEPLOY_KEY}" > srm_devops_deploy_key &&\
          chmod 400 srm_devops_deploy_key &&\
          export GIT_SSH_COMMAND="ssh -i $(pwd)/srm_devops_deploy_key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" &&\
          git clone git@github.com:whiletrue-industries/srm-devops.git &&\
          git config --global user.name "srm-devops CI" &&\
          git config --global user.email "srm-devops-ci@localhost" &&\
          cd srm-devops &&\
          bin/update_yaml.py '{"'"${CHART_NAME}"'":{"image":"'"ghcr.io/whiletrue-industries/${IMAGE_NAME}:${GITHUB_SHA}"'"}}' "helm/${CHART_NAME}/values.auto-updated.yaml" &&\
          git add "helm/${CHART_NAME}/values.auto-updated.yaml" &&\
          git commit -m "update ${CHART_NAME} helm chart auto updated values image" &&\
          git push origin main
        fi
